#!/bin/bash

source ~/.bashrc

sdk use java 21.0.5-oracle
../mx/mx  -p ../graal/compiler/ igv  

# ~/graalvm/mx/mx  -p ~/graalvm/graal/compiler/ igv  

# ../idealgraphvisualizer/bin/idealgraphvisualizer

# ../idealgraphvisualizer/bin/idealgraphvisualizer.exe

# get https://lafo.ssw.uni-linz.ac.at/pub/idealgraphvisualizer/idealgraphvisualizer-1.20-ea624c6066a.zip


