#!/bin/sh
# set -x

CLASSPATH=`mvn -q exec:exec -Dexec.executable=echo -Dexec.args="%classpath"`
if [ -n "$JAVA_HOME" ]; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA="java"
fi
rlwrap "$JAVA" -cp "$CLASSPATH" de.hpi.swa.lox.cli.LoxMain "$@"